CREATE USER KUATRO IDENTIFIED BY KUATRO;
grant create SESSION TO KUATRO;
grant dBA TO KUATRO;


CREATE TABLE Jugadores (
    JugadorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Puntuacion NUMBER,
    Identificacion Number,
    Nombre VARCHAR2(100),
    Ganadas NUMBER,
    Empatadas Number,
    Perdidas Number);
    
CREATE TABLE Partidas(
    PartidaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IDJUGADOR Number,
    IDRival Number,
    Estado VARCHAR2(100),
    Partida Json,
    FechaCreacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_partida_jugador FOREIGN KEY (IDJUGADOR) REFERENCES Jugadores(JugadorID),
    CONSTRAINT fk_partida_rival FOREIGN KEY (IDRival) REFERENCES Jugadores(JugadorID)
);